name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Install Yaml
      run: |
        sudo apt-get update
        sudo apt-get -y install yasm

    - name: Build isa-l
      run: |
        git clone --depth 1 --branch v2.28.0 https://github.com/intel/isa-l.git
        cd isa-l
        ./autogen.sh
        ./configure --prefix=/usr
        make
        sudo make install
        sudo ldconfig

    - name: Build liberasurecode
      run: |
        git clone https://github.com/openstack/liberasurecode.git
        cd liberasurecode
        ./autogen.sh
        ./configure --prefix=/usr
        make
        sudo make install
        sudo ldconfig

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Install & run golangci-lint
      run: |
          wget -q -O - https://github.com/golangci/golangci-lint/releases/download/v1.21.0/golangci-lint-1.21.0-linux-amd64.tar.gz | \
          sudo tar xvz -C /usr/bin --strip-components=1 -f -
          /usr/bin/golangci-lint run --new-from-rev 983e1d15c9877401cfff83356ca0126a313cd20d

    - name: Test
      run: go test -v .

    - name: Build
      run: go build -v .
